# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database_append.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppBook(object):
    def setupUi(self, AppBook):
        AppBook.setObjectName("AppBook")
        AppBook.resize(698, 137)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AppBook.sizePolicy().hasHeightForWidth())
        AppBook.setSizePolicy(sizePolicy)
        AppBook.setMinimumSize(QtCore.QSize(698, 137))
        AppBook.setMaximumSize(QtCore.QSize(698, 137))
        self.gridLayoutWidget = QtWidgets.QWidget(AppBook)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 671, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.editFileName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editFileName.setObjectName("editFileName")
        self.gridLayout.addWidget(self.editFileName, 0, 0, 1, 1)
        self.editAuthorName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editAuthorName.setObjectName("editAuthorName")
        self.gridLayout.addWidget(self.editAuthorName, 0, 2, 1, 1)
        self.cBoxFileGenre = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cBoxFileGenre.setMinimumSize(QtCore.QSize(200, 0))
        self.cBoxFileGenre.setObjectName("cBoxFileGenre")
        self.gridLayout.addWidget(self.cBoxFileGenre, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(AppBook)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 671, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openFileButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openFileButton.setObjectName("openFileButton")
        self.horizontalLayout.addWidget(self.openFileButton)
        self.errorLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayout.addWidget(self.errorLabel)
        self.appendButton = QtWidgets.QPushButton(AppBook)
        self.appendButton.setGeometry(QtCore.QRect(10, 100, 131, 31))
        self.appendButton.setObjectName("appendButton")

        self.retranslateUi(AppBook)
        QtCore.QMetaObject.connectSlotsByName(AppBook)

    def retranslateUi(self, AppBook):
        _translate = QtCore.QCoreApplication.translate
        AppBook.setWindowTitle(_translate("AppBook", "AppBook"))
        self.editFileName.setPlaceholderText(_translate("AppBook", "Название"))
        self.editAuthorName.setPlaceholderText(_translate("AppBook", "Автор"))
        self.openFileButton.setText(_translate("AppBook", "ПРИКРЕПИТЬ ФАЙЛ"))
        self.appendButton.setText(_translate("AppBook", "ДОБАВИТЬ"))
