# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extra_param_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 167)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 139))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(14)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cboxGenre = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cboxGenre.setObjectName("cboxGenre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cboxGenre)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.authorTitle = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Clear Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.authorTitle.setFont(font)
        self.authorTitle.setObjectName("authorTitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.authorTitle)
        self.resetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resetButton.setMinimumSize(QtCore.QSize(150, 31))
        self.resetButton.setMaximumSize(QtCore.QSize(150, 31))
        font = QtGui.QFont()
        font.setFamily("Clear Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("color: white;")
        self.resetButton.setObjectName("resetButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.resetButton)
        self.saveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 31))
        self.saveButton.setMaximumSize(QtCore.QSize(150, 31))
        font = QtGui.QFont()
        font.setFamily("Clear Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("color: white;")
        self.saveButton.setObjectName("saveButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.saveButton)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Extra Parameters"))
        self.label.setText(_translate("Form", "Дополнительные параметры поиска:"))
        self.label_2.setText(_translate("Form", "Жанр:"))
        self.label_3.setText(_translate("Form", "Автор:"))
        self.resetButton.setText(_translate("Form", "СБРОСИТЬ"))
        self.saveButton.setText(_translate("Form", "СОХРАНИТЬ"))
